### ISSUE TITLE
KCEF initialization is not covered in the documentation

### ISSUE THREAD

**Issue by SPC-code** [KevinnZou/compose-webview-multiplatform#101]
I've encountered problem on Windows. The `WebView` shows blank screen for all possible usage scenarios. After some debugging, I found the problem: KCEF returns the state `NEW` and webview then just shows nothing without errors. In order to fix that I had to add 

```kotlin
KCEF.init(
    builder = {
        progress {
            onDownloading {
                println("Download progress: $it%")
            }
        }
        release(true)
    }
)
```

at the start of the application. It is covered [here](https://github.com/DatL4g/KCEF?tab=readme-ov-file#initialize). But webview does not seem to do any initialization or check if the framework is initialized. 

I think that the component should check if the client is available and initialize it properly. In any case, the initialization should be covered in the documentation.

**Comment by KevinnZou** [comment]
@SPC-code Thanks for your feedback. Have you checked this [doc](https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/README.desktop.md) for desktop setup?

**Comment by KevinnZou** [comment]
I will place the reminder in a more noticeable location to prevent it from being overlooked.
