### ISSUE TITLE
Unable to run SampleDesktop App on Mac

### ISSUE THREAD

**Issue by Shabinder** [KevinnZou/compose-webview-multiplatform#11]
See image for reference:
<img width="1085" alt="image" src="https://github.com/KevinnZou/compose-webview-multiplatform/assets/44765050/05ddc836-57f0-482e-aa1d-92f2861fbe43">

**Comment by Shabinder** [comment]
Seems related to this:
https://github.com/KevinnZou/compose-webview-multiplatform/pull/7#issuecomment-1731495840

Readme should be updated since desktop:run doesnt work anymore

**Comment by DATL4G** [comment]
The README requires some changes anyway so we''ll work on this.

I don't own a Mac so I can't test the flags but @KevinnZou does.

**Comment by KevinnZou** [comment]
> Seems related to this: [#7 (comment)](https://github.com/KevinnZou/compose-webview-multiplatform/pull/7#issuecomment-1731495840)
> 
> Readme should be updated since `desktop:runDistributable` doesnt work anymore, while `desktop:run` works

Yes, after switching to the CEF Browser, we have to add the necessary flags to make the desktop app runnable. However, for the ample desktop app in this project, I already add the flags in build.gradle. Does your AS default run `desktop:runDistributable`? My AS default runs `desktop:run` and it works fine. 

Regarding the Readme issue, sorry for the late update! I will update it soon and release the new version.
