### ISSUE TITLE
I want to enable/disable zoom of ios webview using PlatformWebSettings.IOSWebSettings.

### ISSUE THREAD

**Issue by farhazulMullick** [KevinnZou/compose-webview-multiplatform#110]
We can enable/disable support of zoom level through pinch gesture for android webview only. But on iOS zoom is by default enable.

Can we make a toggle in ios websettings for such operations

**Comment by KevinnZou** [comment]
@farhazulMullick Thank you for your suggestion! I have already made a pull request for it and I am planning to release it next week.
