### ISSUE TITLE
Support for force dark theme

### ISSUE THREAD

**Issue by gsrathoreniks** [KevinnZou/compose-webview-multiplatform#113]
I'm looking for support to force dark theme for android for Android version <13 also it would be great if we can inject a css to the loading url to force dark-mode.

**Comment by KevinnZou** [comment]
@gsrathoreniks Can you provide an example of how you implemented it in a raw Android WebView project?

**Comment by KevinnZou** [comment]
@gsrathoreniks Thank you for providing the information. I checked it and discovered that it is only applicable to Android. Could you please elaborate on the plan for injecting a css to the loading URL in order to enforce dark mode? This solution appears to be more universal for both platforms.

**Comment by gsrathoreniks** [comment]
@KevinnZou By css injection I was referring to this [link](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).
If any website does not provide dark mode by itself, we can use this to force dark mode.

**Comment by KevinnZou** [comment]
@gsrathoreniks Thank you for the information! After conducting some research, it appears that iOS WkWebView supports `prefers-color-scheme` by default, while Android requires some configuration. I will add this issue to my plan, but it may take some time to implement since I am currently working on other issues. You are also welcome to submit a PR for it. Thank you for your suggestions again!

**Comment by KevinnZou** [comment]
@gsrathoreniks I have submitted a [PR](https://github.com/KevinnZou/compose-webview-multiplatform/pull/124) to make Android support dark mode. Could you have a review on it?

**Comment by gsrathoreniks** [comment]
I'll have a look and update by this weekend.

**Comment by gsrathoreniks** [comment]
> @gsrathoreniks I have submitted a [PR](https://github.com/KevinnZou/compose-webview-multiplatform/pull/124) to make Android support dark mode. Could you have a review on it?

I'll have a look and update by this weekend.
