### ISSUE TITLE
Android minSdk

### ISSUE THREAD

**Issue by DatL4g** [KevinnZou/compose-webview-multiplatform#119]
The current `minSdk` is set to 24.  
Is there any reason behind that?

The compose core libraries support minSdk 21 as far as I know, I don't really need support for Android 5.0 (SDK 21) but Android 6.0 (SDK 23) would be nice.

**Comment by KevinnZou** [comment]
@DatL4g Thanks for your feedback! Honestly, it is just taken from the JetBrains template. You can downgrade it to 23 once you have verified that it works properly.
