### ISSUE TITLE
Outer composable steals scrolls

### ISSUE THREAD

**Issue by ShmuelCammebys** [KevinnZou/compose-webview-multiplatform#123]
When the WebView is too small to display its contents, it displays scrollbars. However, in my use case, the WebView is embedded in a horizontally scrolling tab pager, and the width has a max value. Horizontal scrolls are stolen by the pager.

**Comment by KevinnZou** [comment]
@ShmuelCammebys Thanks for your feedback! It appears to be expected behavior, and we need to handle it ourselves. Have you tried using Modifier.nestedscroll?

**Comment by ShmuelCammebys** [comment]
@KevinnZou Yes, I did. It did not appear to have any affect.

**Comment by KevinnZou** [comment]
@ShmuelCammebys Could you show me the code?

**Comment by KevinnZou** [comment]
@ShmuelCammebys Thank you for the information! However, I am currently focused on resolving an issue at my company and may not have the time to look it in depth. I did take a quick look and believe that the `PagerDefaults.pageNestedScrollConnection` may not be sufficient to handle the nested scroll issue. I think we will need to create a custom nestedScrollConnection that intercepts the scroll of the pager and allows the WebView to scroll first. However, we currently do not have a scroll method available for the WebView. Therefore, you may need to wait until I have the time to add this feature. Alternatively, you are welcome to submit a pull request if you cannot wait.

BTW, I recommend checking out this library [link to library](https://github.com/KevinnZou/compose-nestedscroll-webview) for guidance on implementing nested scrolling with a webview inside an outer container.

**Comment by Sternbach-Software** [comment]
Was this fixed?

**Comment by rsavutiu** [comment]
Adding pageNestedScrollConnection does do SOMETHING. my Webview now responds to 2-finger swipes/flings, while the parent Pager still answers to single finger flings.
```
HorizontalPager(
                state = pagerState, beyondBoundsPageCount = 3,
                pageNestedScrollConnection = PagerDefaults.pageNestedScrollConnection(state=pagerState, orientation=Orientation.Horizontal))
{ page ->
```
