### ISSUE TITLE
Render In Dark theme

### ISSUE THREAD

**Issue by ShmuelCammebys** [KevinnZou/compose-webview-multiplatform#125]
Currently, if the system is in dark theme, the text is still rendered as if in light theme (default), which can potentially be illegible. This feature request is to follow the dark theme preference of the system when rendering HTML, or add an argument to prefer or force dark theme. Related but distinct from #113 . 
![Screenshot 2024-03-21 at 10 48 39 AM](https://github.com/KevinnZou/compose-webview-multiplatform/assets/144174211/f1e74478-8ec7-45dd-9e87-c9ca5d2c58e1)

**Comment by ShmuelCammebys** [comment]
![Uploading Screenshot 2024-03-21 at 10.48.39 AM.png…]()

**Comment by KevinnZou** [comment]
@ShmuelCammebys Thank you for your suggestions! In this [PR](https://github.com/KevinnZou/compose-webview-multiplatform/pull/124), we will detect the system's dark mode and use `WebSettingsCompat.setForceDark` to change the webview's dark mode. This PR should resolve your issue. If you have any further questions, please let me know.
