### ISSUE TITLE
Wiki Improvement

### ISSUE THREAD

**Issue by DATL4G** [KevinnZou/compose-webview-multiplatform#13]
We have to think of a proper way to document certain thinks.

The current documentation is a bit confusing.
We could either use the Wiki feature by GitHub or maybe something like [Decompose](https://arkivanov.github.io/Decompose/) did.

P.S. please add the following to the desktop ReadMe

```markdown
> **Note**
> Make sure to exclude the `installDir` from upstreaming by adding it to the `.gitignore`.
> The downloaded files are platform-specific and therefore differ to each user.
```

**Comment by Shabinder** [comment]
>  I'm more focused on addressing technical issues and enhancing the capabilities of the components.

Makes sense. 👍

**Comment by DATL4G** [comment]
If we clean-up the project properly we could easily do something like this https://datl4g.github.io/KCEF/

**Comment by KevinnZou** [comment]
> If we clean-up the project properly we could easily do something like this https://datl4g.github.io/KCEF/

Cool! How did you make it?

**Comment by DATL4G** [comment]
Pretty easy we just have to really clean-up the project

* make sure example app related things are not in library module
* set the desired class and method visibility in library module
* document all methods and classes

Then we just have to apply the [Dokka Plugin](https://github.com/Kotlin/dokka) and write a [GitHub Action](https://github.com/DATL4G/KCEF/blob/master/.github/workflows/wiki.yml)

**Comment by KevinnZou** [comment]
Thank you for your instructions! The main issue with this project is that the library module is not separate and is mixed with the example app. I will promptly clean up the project and create a Wiki similar to yours.
