### ISSUE TITLE
Possibility of using custom URL scheme/protocol

### ISSUE THREAD

**Issue by cayolblake** [KevinnZou/compose-webview-multiplatform#132]
@KevinnZou is it possible to use custom URL schemes/protocols? Employing WKURLSchemeHandler on iOS and its alternative in Android.

**Comment by KevinnZou** [comment]
@cayolblake Are you requiring the functionality we discussed in this [issue](https://github.com/KevinnZou/compose-webview-multiplatform/issues/87)?

**Comment by cayolblake** [comment]
Yes. It it's very important in most apps with WebView dependency.

**Comment by KevinnZou** [comment]
@cayolblake Yes, we are also trying to provide that feature. However, we are encountering some troubles. You can check the issue above for details. But I will keep working on solving them. I apologize for any inconvenience caused by that issue.

**Comment by cayolblake** [comment]
@KevinnZou all your efforts are outstandingly appreciated and your work benefits a lot 🌹👍💪

Hopefully this gets resolved soon 🤞

**Comment by KevinnZou** [comment]
@cayolblake I have implemented a basic interception in the latest version 1.9.8. Please follow these [instructions](https://github.com/KevinnZou/compose-webview-multiplatform?tab=readme-ov-file#request-interceptor) to conduct a test and let me know if you encounter any issues.
