### ISSUE TITLE
Remove material dependency

### ISSUE THREAD

**Issue by kalinjul** [KevinnZou/compose-webview-multiplatform#136]
Hi,
thanks for the nice library!

I noticed that you pull in compose.material here:
https://github.com/KevinnZou/compose-webview-multiplatform/blob/a45c21790b3b0dba1bec6b5cca6245d1f5775ead/webview/build.gradle.kts#L42

I think it is not required for anything but the sample app, so it would be nice to have it removed :)
My App uses material3 and pulls in material2 just for the webview.

Kind Regards,
Julian

**Comment by KevinnZou** [comment]
@kalinjul Thanks for your suggestion! I will fix it in the next version. Thanks!
