### ISSUE TITLE
Is it possible to support KCEFClientProvider for DesktopWebView?

### ISSUE THREAD

**Issue by bulletjet786** [KevinnZou/compose-webview-multiplatform#138]
Firstly, thank you very much for providing this library. 

**Backgroup**
I hope to be able to use a WebView within Compose for Desktop with the JetBrains Runtime. This enables the elimination of the necessity for both downloading JBR/JCEF and restarting the application. 
see: https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/webview/src/desktopMain/kotlin/com/multiplatform/webview/web/WebView.desktop.kt

**I Think**
By employing the JetBrains Runtime, I should be able to initialize a JCEF Client and subsequently instantiate a KCEFClient. If PlatformWebSettings.DesktopWebSettings supports a KCEFClientProvider, utilizing the KCEFClientProvider provided within DesktopWebSettings in DesktopWebView would eliminate the dependency on the initialization process of KCEF itself.

**In Progress**
I have initiated a PR and a Issue:
https://github.com/DatL4g/KCEF/pull/11
https://github.com/DatL4g/KCEF/issues/9

**Comment by KevinnZou** [comment]
@bulletjet786 Thank you for your valuable suggestions! @DatL4g is responsible for the desktop side of the project. However, it appears that he is currently occupied with other tasks and may not be able to devote much time to this project. Therefore, you are welcome to submit a pull request, and @DatL4g will review it before releasing it. Thanks again!

**Comment by bulletjet786** [comment]
I'm sorry for the delayed reply. While I'm not an experienced Kotlin user or well-versed in client-side software development, my expertise lies in crafting server-side applications using Go. That said, I'm enthusiastic about contributing to projects like KCEF and compose-webview-multiplatform. However, due to constraints on my personal time, I can only offer a limited level of support. @KevinnZou @DatL4g
