### ISSUE TITLE
Post URL with form data

### ISSUE THREAD

**Issue by Drabu** [KevinnZou/compose-webview-multiplatform#145]
Post URL with form data is missing. I could find the postURL but it posts the information in body and not as a form data

**Comment by KevinnZou** [comment]
@Drabu Thanks for your feedback. Could you specify the platforms where you are encountering the issue?

**Comment by Drabu** [comment]
I could not find any method in the lib which would allow to load a POST URL in WebView where i can add form data to it. So this is not specific to any platform. Since there is no method i could find so i am assuming it is not working platform.

**Comment by KevinnZou** [comment]
@Drabu Currently, we only have one `postUrl` method.
```
/**
 * Posts the given data to the given URL.
 *
 * @param url The URL to post the data to.
 * @param postData The data to post.
 */
fun postUrl(
    url: String,
    postData: ByteArray,
)
```

On Android, it will just call `postUrl` below. Does that meet your request? If not, which method in Android are you using?
```
/**
 * Loads the URL with postData using "POST" method into this WebView. If url
 * is not a network URL, it will be loaded with {@link #loadUrl(String)}
 * instead, ignoring the postData param.
 *
 * @param url the URL of the resource to load
 * @param postData the data will be passed to "POST" request, which must be
 *     be "application/x-www-form-urlencoded" encoded.
 */
public void postUrl(@NonNull String url, @NonNull byte[] postData) {
    checkThread();
    if (URLUtil.isNetworkUrl(url)) {
        mProvider.postUrl(url, postData);
    } else {
        mProvider.loadUrl(url);
    }
}
```
