### ISSUE TITLE
1.8.6版本ios背景色问题

### ISSUE THREAD

**Issue by riveronly** [KevinnZou/compose-webview-multiplatform#159]
<img width="224" alt="Snipaste_2024-05-19_17-24-32" src="https://github.com/KevinnZou/compose-webview-multiplatform/assets/42523296/9f63b368-b339-476e-809e-986972f4dd16">
（1.8.6）
<img width="224" alt="Snipaste_2024-05-19_17-24-00" src="https://github.com/KevinnZou/compose-webview-multiplatform/assets/42523296/3cd25cb4-6f2b-4584-85ea-46a9e120ac83">
（1.8.4）

1.8.6版本加入的ios背景色设置，可能导致了全屏幕的webview无法覆盖状态栏的背景。
测试网页：https://riveronly.github.io/pure_divination/

**Comment by KevinnZou** [comment]
@riveronly Thanks for your feedback! Could you please provide more details about the problem? Which picture represents the expected behavior? Additionally, it would be helpful if you could provide the test code.

**Comment by riveronly** [comment]
> @riveronly Thanks for your feedback! Could you please provide more details about the problem? Which picture represents the expected behavior? Additionally, it would be helpful if you could provide the test code.

<img width="553" alt="Snipaste_2024-05-19_17-24-00" src="https://github.com/KevinnZou/compose-webview-multiplatform/assets/42523296/c3d73d17-17af-479d-ade9-cb054eaa8904">
这张图片是预期的效果，既状态栏是沉浸效果。不会额外给白色的背景色。测试代码可以基于您的示例代码，仅改变URL访问https://riveronly.github.io/pure_divination/即可。

**Comment by riveronly** [comment]
> > @riveronly Thanks for your feedback! Could you please provide more details about the problem? Which picture represents the expected behavior? Additionally, it would be helpful if you could provide the test code.
> 
> <img alt="Snipaste_2024-05-19_17-24-00" width="553" src="https://private-user-images.githubusercontent.com/42523296/331861707-c3d73d17-17af-479d-ade9-cb054eaa8904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTIzMzksIm5iZiI6MTcxNjExMjAzOSwicGF0aCI6Ii80MjUyMzI5Ni8zMzE4NjE3MDctYzNkNzNkMTctMTdhZi00NzlkLWFkZTktY2IwNTRlYWE4OTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA5NDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjBmYjllMzVkNzE4ZjY1YzJkOTczMTUwMmNmMjE5NjNhMmI3ZmNiZmNiMDc3NjQ1YjVlYmY4ZGQzNDE3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iBHPvnvuz1sc5bW66cQNMYQHNFjcnIu_QN3vqvYCDTQ"> 这张图片是预期的效果，既状态栏是沉浸效果。不会额外给白色的背景色。测试代码可以基于您的示例代码，仅改变URL访问https://riveronly.github.io/pure_divination/即可。

需要开启enableEdgeToEdge

**Comment by riveronly** [comment]
no white backgroudColor is expected behavior

need use ``enableEdgeToEdge()``

and code:

````
@Composable
internal fun App() {
    val initialUrl = "https://riveronly.github.io/pure_divination/"
    val navigator = rememberWebViewNavigator()
    val state = rememberWebViewState(url = initialUrl)
    LaunchedEffect(Unit) {
        state.webSettings.apply {
            logSeverity = KLogSeverity.Debug
            customUserAgentString =
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1) AppleWebKit/625.20 (KHTML, like Gecko) Version/14.3.43 Safari/625.20"
        }
    }
    Column {
        val loadingState = state.loadingState
        if (loadingState is LoadingState.Loading) {
            LinearProgressIndicator(
                progress = { loadingState.progress },
                modifier = Modifier.fillMaxWidth(),
            )
        }
        WebView(
            state = state,
            modifier = Modifier.fillMaxSize().border(5.dp, Color.Red, RectangleShape),
            navigator = navigator,
        )
    }
}
````

**Comment by riveronly** [comment]
Also, the sliding effect is different. In 1.8.4 it is a sliding view on the background. In 1.8.6 and later, the entire background is slid

**Comment by KevinnZou** [comment]
@msasikanth It seems that the problems are caused by this [PR](https://github.com/KevinnZou/compose-webview-multiplatform/pull/95). Could you have a look at it?

**Comment by msasikanth** [comment]
This is in the latest version of the library. It seems to be working as intended?

![image](https://github.com/KevinnZou/compose-webview-multiplatform/assets/6140516/9523b14a-18f6-4568-bc71-3e266942ef15)

![image](https://github.com/KevinnZou/compose-webview-multiplatform/assets/6140516/77dca5ff-b013-4178-89cf-64ecd4e38b6f)

**Comment by riveronly** [comment]
> This is in the latest version of the library. It seems to be working as intended?
> 
> ![image](https://private-user-images.githubusercontent.com/6140516/331910686-9523b14a-18f6-4568-bc71-3e266942ef15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzEyNTQsIm5iZiI6MTcxNjE3MDk1NCwicGF0aCI6Ii82MTQwNTE2LzMzMTkxMDY4Ni05NTIzYjE0YS0xOGY2LTQ1NjgtYmM3MS0zZTI2Njk0MmVmMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDIwOTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE5OGQzMTM5ZWI1ZGExMTI0MDYzMGQwNTljOGI1MTk3YjhjNjAxMWNkNzZjY2JiMDg3YTYwYzA0ODFmZTljZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X05vpwMn_NpyJXevbKzEAWXQ3gXe56XueR6MDzNtI-I)
> 
> ![image](https://private-user-images.githubusercontent.com/6140516/331910703-77dca5ff-b013-4178-89cf-64ecd4e38b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzEyNTQsIm5iZiI6MTcxNjE3MDk1NCwicGF0aCI6Ii82MTQwNTE2LzMzMTkxMDcwMy03N2RjYTVmZi1iMDEzLTQxNzgtODljZi02NGVjZDRlMzhiNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDIwOTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWJkZTAwZWVhN2MyOGIxMGZkNWQ2MTFiNmE2M2JmY2U4YmNlYzZjYTA1YjQzMDZkMGVlNWIxYzI5NTYxNWRjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wGwNAMNZAlQeZjTr0sQZzBGk7B1kjT9YbTPB2QPIaz4)

If the webView is full screen, it should be displayed below the status bar. It avoids the status bar which is not expected. The picture you posted seems to mask the issue because of the dark background and dark theme, but the second picture does

**Comment by msasikanth** [comment]
@KevinnZou the issue seems to be WebView not going edge to edge? The background does color does go below the status bar. So maybe a safe area issue for the webview on iOS?

**Comment by riveronly** [comment]
In fact, there is also a sliding problem, which shows a completely different sliding effect in 4 and 6. In the latest version 6, you can slide the entire background color, which is strange. I can run my simple project and change the version dependency to observe the difference. Https://github.com/riveronly/river.git

**Comment by KevinnZou** [comment]
> @KevinnZou the issue seems to be WebView not going edge to edge? The background color does go below the status bar. So maybe a safe area issue for the webview on iOS?

@msasikanth Yes, it seems to be a safe area issue. However, according to @riveronly's's description, this issue only appeared after version 1.8.6. Thus, it should be caused by the changes in this version.

The main changes are below:
```
setOpaque(false)
val composeBackgroundColor = state.webSettings.backgroundColor
val backgroundColor =
    UIColor(
        red = composeBackgroundColor.red.toDouble(),
        green = composeBackgroundColor.green.toDouble(),
        blue = composeBackgroundColor.blue.toDouble(),
        alpha = composeBackgroundColor.alpha.toDouble(),
    )
setBackgroundColor(backgroundColor)
scrollView.setBackgroundColor(backgroundColor)
```

Is that because we also setBackgroundColor for scrollView?
