### ISSUE TITLE
Ktor 3.0.0-beta-1 support

### ISSUE THREAD

**Issue by artalejo** [KevinnZou/compose-webview-multiplatform#164]
Hello there,

In my KMM project I am currently using Ktor 3.0.0-beta-1 version for several reasons, the problem is that when compiling and trying to open a webview in my compose desktop app an issue with the Content Negotiation arises.

`java.lang.NoClassDefFoundError: io/ktor/client/plugins/contentnegotiation/ContentNegotiation
	at dev.datlag.kcef.step.fetch.PackageDownloader$downloadPackage$client$1.invoke(PackageDownloader.kt:39)
	at dev.datlag.kcef.step.fetch.PackageDownloader$downloadPackage$client$1.invoke(PackageDownloader.kt:37)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:42)`

**Comment by KevinnZou** [comment]
@DatL4g Could you have a look at this issue?

**Comment by DatL4g** [comment]
On Backlog until there is a stable release

**Comment by SamC-Apadmi** [comment]
Any change here folks?

**Comment by mixeden** [comment]
+1 here, getting same error on 3.0.0

**Comment by SamC-Apadmi** [comment]
I've just used v1.6.0 for now and that works.
@DatL4g I'm happy to create a PR on KCEF and on this repo if you'd be able to review them? If you're offline completely at the moment though I'll hold off

**Comment by DatL4g** [comment]
@SamC-Apadmi please go ahead, I'll review it

**Comment by SamC-Apadmi** [comment]
@DatL4g PR open [here](https://github.com/DatL4g/KCEF/pull/17). If you're happy and we can get a build out of that library I'll then PR into this repo for that change.

**Comment by DatL4g** [comment]
@KevinnZou KCEF [2024.04.20.3](https://github.com/DatL4g/KCEF/releases/tag/v2024.04.20.3) supports Ktor 3.x now

BTW since [2024.04.20.2](https://github.com/DatL4g/KCEF/releases/tag/v2024.04.20.2) it's possible to use KCEF with the JetBrains JCEF JDK (so no downloading) however there is no working example how to set it up yet.

**Comment by SamC-Apadmi** [comment]
I think we still need to merge [this](https://github.com/KevinnZou/compose-webview-multiplatform/pull/240) before closing this issue?
