### ISSUE TITLE
rememberSaveableWebViewState does not work when webview is inside Lazy Column (Android)

### ISSUE THREAD

**Issue by LaatonWalaBhoot** [KevinnZou/compose-webview-multiplatform#166]
As the title suggests. The webview does not save the state when in LazyColumn
Code
```
val state = rememberSaveableWebViewState(url = "https://google.com")
val navigator = rememberWebViewNavigator()
WebView(state = state, modifier = Modifier.fillMaxWidth().height(300.dp), navigator = navigator)
```

This however works
```
val state = rememberWebViewState(url = "https://google.com")
val navigator = rememberWebViewNavigator()
WebView(state = state, modifier = Modifier.fillMaxWidth().height(300.dp), navigator = navigator)
```

But the webview reloads on coming back to the same screen. @KevinnZou Is this an expected behaviour?

**Comment by KevinnZou** [comment]
@LaatonWalaBhoot Thanks for your feedback! This issue may relate to [another issue](https://github.com/KevinnZou/compose-webview-multiplatform/issues/169). You can follow up on that issue to get the update.
