### ISSUE TITLE
Add option for media playback without gesture

### ISSUE THREAD

**Issue by nielsvanvelzen** [KevinnZou/compose-webview-multiplatform#172]
It would be nice if support for [media playback without user gesture](https://developer.android.com/reference/android/webkit/WebSettings.html#setMediaPlaybackRequiresUserGesture(boolean)) could be added for Android.

**Comment by KevinnZou** [comment]
@nielsvanvelzen Thanks for your feedback! I will add this feature to our plan. You are welcome to submit a pull request for it if you are interested.
