### ISSUE TITLE
Download files

### ISSUE THREAD

**Issue by nickfaces** [KevinnZou/compose-webview-multiplatform#177]
Hi!

Can we use webview to dowload files? In the browser, when I click on the file download button, the file manager opens or the download starts automatically.
Nothing happens in the webview.

**Comment by KevinnZou** [comment]
@nickfaces Thanks for your feedback! We are unable to support this with just simple settings. It needs to be implemented for all platforms using the native method. Unfortunately, we do not have enough resources to do so. If you are willing to do it, you are welcome to submit a PR. Thank you!
