### ISSUE TITLE
 Could not find org.jogamp.gluegen:gluegen-rt:2.5.0.

### ISSUE THREAD

**Issue by YuXunSTC** [KevinnZou/compose-webview-multiplatform#179]
遇到个错误     
Execution failed for task ':composeApp:desktopRun'.
> Could not resolve all files for configuration ':composeApp:desktopRuntimeClasspath'.
   > Could not find org.jogamp.gluegen:gluegen-rt:2.5.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jogamp/gluegen/gluegen-rt/2.5.0/gluegen-rt-2.5.0.pom
     Required by:
         project :composeApp > io.github.kevinnzou:compose-webview-multiplatform:1.9.10 > io.github.kevinnzou:compose-webview-multiplatform-desktop:1.9.10 > dev.datlag:kcef:2024.01.07.1 > dev.datlag:jcef:2024.01.07.1
   > Could not find org.jogamp.jogl:jogl-all:2.5.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jogamp/jogl/jogl-all/2.5.0/jogl-all-2.5.0.pom
     Required by:
         project :composeApp > io.github.kevinnzou:compose-webview-multiplatform:1.9.10 > io.github.kevinnzou:compose-webview-multiplatform-desktop:1.9.10 > dev.datlag:kcef:2024.01.07.1 > dev.datlag:jcef:2024.01.07.1

https://repo.maven.apache.org/maven2/org/jogamp/gluegen/gluegen-rt/2.5.0/gluegen-rt-2.5.0.pom 
这个地址访问是404

**Comment by YuXunSTC** [comment]
Android iOS 都没问题，desktop 会报这个错误

**Comment by KevinnZou** [comment]
@YuXunSTC Please refer to this [instruction](https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/README.desktop.md#dependencies).

**Comment by andreshl** [comment]
how do you repare ?
