### ISSUE TITLE
WebRequestInterceptResult.Reject gives unwanted stop for other urls too.

### ISSUE THREAD

**Issue by AttilaBarany** [KevinnZou/compose-webview-multiplatform#184]
Hi,

I have a problem because on android the interception reject calls webview.stopLoading() additionaly on top of returning true for shouldOverrideUrlLoading. Only return true should be enough which prevents to load that specific url. I tried with normal androidview and I am sure that stopLoading causes the problem (additional forwarding will not trigger anymore if stoploading is called before returning true). This is unwanted behaviour because we would like to intercept only one specific url at a time, but not all. 

Cheers:)

<img width="441" alt="Screenshot 2024-06-26 at 17 12 22" src="https://github.com/KevinnZou/compose-webview-multiplatform/assets/40792011/9c8782be-3f1c-4e12-b85f-372a4591c4bd">

**Comment by AttilaBarany** [comment]
Of course stoploading is ok at modify, make sense, but not in reject.

**Comment by KevinnZou** [comment]
@AttilaBarany Thanks for your suggestion! I will add it to the plan. You are also welcome to submit a PR to fix it!

**Comment by AttilaBarany** [comment]
> @AttilaBarany Thanks for your suggestion! I will add it to the plan. You are also welcome to submit a PR to fix it!

Thanks for the chance. (https://github.com/KevinnZou/compose-webview-multiplatform/pull/185)
