### ISSUE TITLE
Add support for requesting permissions

### ISSUE THREAD

**Issue by minmax1993** [KevinnZou/compose-webview-multiplatform#188]
Thank you for developing this awesome library and sorry for creating a new issue on requesting permissions.

Do you have any updates on requesting permissions like Camera, Mic?
If it's not on todo list, could you provide samples for using JSBridge to request permissions?
any solution would be greatly appreciated!

**Comment by KevinnZou** [comment]
@minmax1993 I'm sorry, but requesting permissions is not included in our plan for the WebView. We are unable to handle all the necessary permissions for developers. If you require this feature, it would be better to fork this project and add your logic for permissions to it directly. Additionally, there is a sample on how to use JSBridge in the documentation that you can follow to get started.

**Comment by KevinnZou** [comment]
@minmax1993 You are also welcome to submit a PR to support this feature! Thanks!
