### ISSUE TITLE
Background color of Website does not change if it has a dark mode toggle

### ISSUE THREAD

**Issue by Vaibhav2002** [KevinnZou/compose-webview-multiplatform#191]
If I dont use `algorithmic darkening` and the website has in-built theme toggle
The light mode of the website still has a dark background
This only happens if the device is in dark theme, and works great in light theme

### Reproducer
```kotlin
val state = rememberWebViewState("https://www.medial.app")
DisposableEffect(Unit) {
    state.webSettings.apply {
        isJavaScriptEnabled = true
        androidWebSettings.apply {
            domStorageEnabled = true
            safeBrowsingEnabled = true
            isAlgorithmicDarkeningAllowed = false
        }
    }
    onDispose { }
}

WebView(
    state = state,
    modifier = Modifier.fillMaxSize().navigationBarsPadding()
)
```

### Recording

https://github.com/KevinnZou/compose-webview-multiplatform/assets/64367926/652fc3b4-0f12-4603-918e-b4ba488e9cdf

**Comment by KevinnZou** [comment]
@Vaibhav2002 Thanks for your feedback! Did you test it with raw Android Webview? It seems to be the problem with it.
