### ISSUE TITLE
iOS error with latest navigation-compose

### ISSUE THREAD

**Issue by mjdenham** [KevinnZou/compose-webview-multiplatform#196]
If I upgrade the navigation-compose library to version 2.8.0-alpha08 in order to use the new type-safe navigation objects the webview still works on Android but there is an error from WebViewNavigator when running iOS:

IrLinkageError: Function 'UIKitView' can not be called: No function found for symbol 'androidx.compose.ui.interop/UIKitView

I have attached a stacktrace.
[iosKmpWebviewCrash.txt](https://github.com/user-attachments/files/16197306/iosKmpWebviewCrash.txt)

The small test project I am working on is here: https://github.com/mjdenham/KMP-Compose-Bible-App

**Comment by KevinnZou** [comment]
@mjdenham What's your CMP version?

**Comment by mjdenham** [comment]
I am using the latest stable which is 1.6.10.  I tried updating the compose version to 1.7.0-alpha01 but got the same error.
Do you think the compose version could cause the error in:
com.multiplatform.webview.web#IOSWebView

**Comment by yuroyami** [comment]
This is probably a binary compatibility issue. The library source code works fine when I merge it with my own code, but when I add it as a library it doesn't.

**Comment by Matcha-xiaobin** [comment]
我这也有相同的问题。

**Comment by pavelrukin** [comment]
I also have the same problem. Please tell me did you manage to solve it.
`kotlin.native.internal.IrLinkageError: Function 'UIKitView' can not be called: No function found for symbol 'androidx.compose.ui.interop/UIKitView|UIKitView`

**Comment by yuroyami** [comment]
@pavelrukin The workaround you can go for as of now, is to copy the source code files into your codebase rather than using this as an external dependency.

**Comment by NaiRo94s** [comment]
I receive the same error using the latest compose multiplatform version. [1.7.0-alpha02](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.7.0-alpha02)

**Comment by KevinnZou** [comment]
It seems that we need to update the CMP version to 1.7.0-alpha01 to make it compatible with the latest navigation-compose library. However, we will not upgrade until the stable version is released.

**Comment by Egi10** [comment]
I'm getting the same error on my iOS device with CMP 1.6.11

**Comment by KevinnZou** [comment]
> I'm getting the same error on my iOS device with CMP 1.6.11

2.8.0-alpha08 only works with CMP 1.7.0-*. I would recommend you downgrade to the stable version first.

**Comment by maicol07** [comment]
@KevinnZou can you publish an alpha/beta version that supports the new compose? So in the meantime, we can use it

**Comment by Psycadelik** [comment]
I also have the same issue on ios but the webview works just fine on Android:
```
Uncaught Kotlin exception: kotlin.native.internal.IrLinkageError: Function 'UIKitView' can not be called: No function found for symbol 'androidx.compose.ui.interop/UIKitView
```

CMP version - 1.6.10
navigation-compose - 2.8.0-alpha08
kotlin - 2.0.0

**Comment by fluxxion82** [comment]
@KevinnZou Having an alpha/beta version that uses the latest CMP and navigation libraries would be a good idea and help a lot of people. Copying files into our project isn't a good workaround.

**Comment by KevinnZou** [comment]
@fluxxion82 Thanks for your feedback! I will release an alpha version next week. Sorry for the inconvenience.

**Comment by mjdenham** [comment]
Thanks Kevinn, 1.9.40-alpha01 works great.
