### ISSUE TITLE
Scrolling doesn't work as it should (iOS)

### ISSUE THREAD

**Issue by BlendMax** [KevinnZou/compose-webview-multiplatform#228]
With the latest version 1.9.40-alpha01 I have problems with scrolling in webview (iOS devices). The problem is that when I try to scroll, the gesture is not recognized immediately, I need to hold my finger for the scrolling to work. If I try to make a gesture quickly, then the scrolling does not work

**Comment by msasikanth** [comment]
@KevinnZou this can be closed with #231 ?
