### ISSUE TITLE
Nothing shown on iOS

### ISSUE THREAD

**Issue by NikiforosDesquared** [KevinnZou/compose-webview-multiplatform#233]
Greetings, i am trying to add the library at my Compose Multiplatform project, and it works fine on the Android side, but it shows nothing on iOS even with the simplest of examples.
```
val newState = rememberWebViewState("https://www.google.com")
WebView(newState)
```
I get nothing on the logs.
I tried on:

1. device iPhone XS,  iOS 15.4.1 
2. simulator iPhone 15 Pro, iOS 17.2

i am using compose-plugin: "1.6.11" and version "1.9.20" of the library, the app crashes before showing anything if i use version "1.9.40-alpha03".

Any help is appreciated

**Comment by NikiforosDesquared** [comment]
**Update:**
I managed to use 1.9.40-alpha03 with compose-plugin 1.7.0-beta02, but still, iOS draws nothing

**Comment by KevinnZou** [comment]
> **Update:** I managed to use 1.9.40-alpha03 with compose-plugin 1.7.0-beta02, but still, iOS draws nothing

Did you apply Modifier.fillMaxSize?

**Comment by NikiforosDesquared** [comment]
> > **Update:** I managed to use 1.9.40-alpha03 with compose-plugin 1.7.0-beta02, but still, iOS draws nothing
> 
> Did you apply Modifier.fillMaxSize?

Dear Kevinn, thanks for your reply, i had the modifier set to Modifier.fillMaxSize in a previous attempt, but it was not working. Turns out that since it was a nested component, i had to set the modifier like that in all parents.
It was weird that this wwas working on Android. 

Thanks for your reply.

**Comment by JagadishaIncture** [comment]
Same issue fixed by adding Modifier in Desktop as well
