### ISSUE TITLE
App CRASH on ios 18 when update jetbrains.androidx.navigation

### ISSUE THREAD

**Issue by DmitriSerhienko** [KevinnZou/compose-webview-multiplatform#248]
Hi, I use U library version "1.9.20" and just start receive crashes on ios, when I update library from 
navigation-compose = { "org.jetbrains.androidx.navigation:navigation-compose:2.7.0-alpha07" }
to
navigation-compose = { "org.jetbrains.androidx.navigation:navigation-compose:2.8.0-alpha10" }
My usage:
val webViewState = rememberWebViewState(url = url, additionalHttpHeaders = headers)
DisposableEffect(Unit) {
        webViewState.webSettings.apply {
            isJavaScriptEnabled = true
            supportZoom = true
        }
        onDispose { }
    }
Box(modifier = Modifier.fillMaxSize()){
    WebView(
                state = webViewState,
                modifier = Modifier.fillMaxSize(),
                navigator = navigator,
            )
}

**If I comment this:** WebView(state = webViewState, modifier = Modifier.fillMaxSize()) - app **dont crash** on rhis screen
Test on ios 18 version

**This is in my log:**
kotlin.native.internal.IrLinkageError: Function 'UIKitView' can not be called: No function found for symbol 'androidx.compose.ui.interop/UIKitView|UIKitView(kotlin.Function0<0:0>;androidx.compose.ui.Modifier;kotlin.Function1<0:0,kotlin.Unit>?;androidx.compose.ui.graphics.Color;kotlin.Function1<0:0,kotlin.Unit>?;kotlin.Function2<0:0,kotlinx.cinterop.CValue<platform.CoreGraphics.CGRect>,kotlin.Unit>?;kotlin.Boolean;androidx.compose.runtime.Composer?;kotlin.Int;kotlin.Int){0§<platform.UIKit.UIView>}[0]'

Uncaught Kotlin exception:     at 0   GlobinoSales                        0x1069d882b        kfun:kotlin.Throwable#<init>(kotlin.String?){} + 119 

    at 1   GlobinoSales                        0x1069d19f7        kfun:kotlin.Error#<init>(kotlin.String?){} + 115 

    at 2   GlobinoSales                        0x106a0d967        kfun:kotlin.native.internal.IrLinkageError#<init>(kotlin.String?){} + 115 

    at 3   GlobinoSales                        0x106a0da2b        kfun:kotlin.native.internal#ThrowIrLinkageError(kotlin.String?){}kotlin.Nothing + 175

**Comment by idan-fido** [comment]
Same here, seems to be solved on 1.9.40-alpha

**Comment by DmitriSerhienko** [comment]
> Same here, seems to be solved on 1.9.40-alpha

I hope)

**Comment by DmitriSerhienko** [comment]
1.9.40-alpha04  and compose-plugin ver 1.7.1 solved this problem
