### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by savan-ixfi** [KevinnZou/compose-webview-multiplatform#3]
in IOSWebView class

wkWebView.loadHTMLString(
            string = concat,
            baseURL = baseUrl?.let { NSURL(string = it) },
        )

please replace above code with below code

wkWebView.loadHTMLString(
                string = concat,
                baseURL = baseUrl?.let { NSURL.URLWithString(it) },
            )

**Comment by KevinnZou** [comment]
Hi, thanks for your suggestion! you closed the issue by yourself is that because they are the same in KN? Or it is better to use NSURL.URLWithString(it)?

**Comment by savan-ixfi** [comment]
> Hi, thanks for your suggestion! you closed the issue by yourself is that because they are the same in KN? Or it is better to use NSURL.URLWithString(it)?

for html data NSURL(string = it) give me NullPointerException

**Comment by KevinnZou** [comment]
> > Hi, thanks for your suggestion! you closed the issue by yourself is that because they are the same in KN? Or it is better to use NSURL.URLWithString(it)?
> 
> for html data NSURL(string = it) give me NullPointerException

I think it may be because NSURL() does not accept null input but NSURL.URLWithString(it) does. Anyway, I will change to NSURL.URLWithString(it). Thanks again for your suggestion!
