### ISSUE TITLE
Background Color Not Applied When Using Hex Color Codes in Kotlin Multiplatform for Desktop

### ISSUE THREAD

**Issue by ariel10aguero** [KevinnZou/compose-webview-multiplatform#39]
**Description**:
There's an issue with the background color not updating to the specified hex color code in a Kotlin Multiplatform for Desktop project. The background remains white, despite the hex code being set correctly in the code. Using named colors like "black" seems to work fine, but hex codes do not.

**Steps to Reproduce**:
1. Integrate the following Kotlin code into a Kotlin Multiplatform project for Desktop.
2. Observe that the WebView component's background color remains white instead of changing to the specified hex color code "#222E3A".

**Expected Behavior**:
The WebView component's background should display the color corresponding to the hex color code given.

**Actual Behavior**:
The WebView's background color remains white regardless of the hex color code provided.

**Code Snippet**:

```kotlin
@Composable
fun BotResponse(
    chatMessage: ChatMessage,
    chatViewModel: ChatViewModel
) {
    chatMessage.botResponse?.let { botResponse ->

        val textColorString = "#FFFFFF"
        val backgroundColorString = "#222E3A"

        val htmlPrefix = "<head><meta name=\"viewport\" content=\"width=device-width, height=device-height, shrink-to-fit=YES\"></head><body style=\"font-family: 'Roboto', sans-serif; color: $textColorString; margin:0px !important; padding:0px!important; background: $backgroundColorString;\"><div id=\"bot-response-container\" style=\"background: $backgroundColorString;\">"
        val htmlSuffix = "</div></body>"
        val contentHtml = htmlPrefix + botResponse + htmlSuffix

        val webViewState = rememberWebViewStateWithHTMLData(
            contentHtml,
            null,
            "utf-8",
            "text/html",
            null
        )

        Column(
            verticalArrangement = Arrangement.Center,
            modifier = Modifier.fillMaxWidth(0.8f)
        ) {
            Row(
                verticalAlignment = Alignment.CenterVertically
            ) {
                WebView(
                    state = webViewState,
                    modifier = Modifier.size(320.dp)
                )
            }
        }
    }
}
```

Environment:

OS: [MacOs 13.4]
Kotlin Version: [1.9.10]
Library Version: [1.6.0]

**Comment by KevinnZou** [comment]
@DatL4g Could you please have a look at this problem?

**Comment by DatL4g** [comment]
Sorry can't deeply look into it, since I had an OP 2 days ago.
I guess this is an old issue which we discussed before already and should be fixed with KCEF.

@ariel10aguero you can try setting the hex code without the `#` prefix, so instead of `#222E3A` try `222E3A`
