### ISSUE TITLE
Cannot obtain Geolocation

### ISSUE THREAD

**Issue by mjacome** [KevinnZou/compose-webview-multiplatform#51]
Websites that are able to request and use your GPS don't seem to be working in the WebView. In an ordinary Android app, one could implement a custom WebChromeClient for this to work, see https://stackoverflow.com/questions/42746222/geolocation-is-not-working-on-android-webview

Any solution to this would be greatly appreciated!

**Comment by minmax1993** [comment]
Thanks for making this awesome library. @KevinnZou 

Do you have any updates on requesting permissions like Camera, Mic? 
Is there any samples can you provide for using JSBridge to request permissions ?
any solution would be greatly appreciated!
