### ISSUE TITLE
Support for scriptMessageHandler on desktop

### ISSUE THREAD

**Issue by tomastiminskas** [KevinnZou/compose-webview-multiplatform#54]
We have implemented this library in a kotlin cross platform application (for desktop) and we need to communicate back and forth with the web app we are loading in a webview. As I could see in the documentation we already have a way to send script messages to the web app using the `evaluateJavaScript` of the `WebViewNavigator` but we don't have a way to implement a `scriptMessageHandler` to receive messages from the web app to the app we are building.

Any plan to support this soon? Thanks in advance

**Comment by KevinnZou** [comment]
@tomastiminskas Thank you for your feedback! If I understand correctly, you are looking for functionality similar to jsbridge. There is already a plan to support this feature, but we are currently encountering some issues. I will continue working on it and anticipate its completion by the end of this month. You can subscribe to this [issue](https://github.com/KevinnZou/compose-webview-multiplatform/issues/31) for updates. Thank you for your patience!

**Comment by tomastiminskas** [comment]
Thanks for your quick response @KevinnZou . I already subscribed to the issue you mentioned.

**Comment by KevinnZou** [comment]
@tomastiminskas It has been released in version [1.8.0](https://github.com/KevinnZou/compose-webview-multiplatform/releases/tag/1.8.0). Please have a try and let me know if you encounter any problems.
