### ISSUE TITLE
desktop上无法使用

### ISSUE THREAD

**Issue by Matcha-xiaobin** [KevinnZou/compose-webview-multiplatform#55]
![image](https://github.com/KevinnZou/compose-webview-multiplatform/assets/5775066/fa91bfde-dfd1-490e-8ee2-6b38b1e3260b)
这是我的使用方式，它在android上一切正常，但是在desktop上出了问题，我没有看到任何错误信息，我不知道该如何查找错误。

**Comment by Matcha-xiaobin** [comment]
运行在 intel 平台的 mac OS 14

**Comment by KevinnZou** [comment]
@Matcha-xiaobin Thank you for your feedback. I would like to know the expected behavior of this page. Can you provide the URL for testing? Additionally, which version of this library are you using?

**Comment by KevinnZou** [comment]
The test URL refers to the URL you are loading into the WebView. I would like to have it to confirm whether the URL is causing the issue. I am using an Intel Mac and it is working well with this code. Can you give it a try as well?
```
MaterialTheme {
    val webViewState =
        rememberWebViewState("https://github.com/KevinnZou/compose-webview-multiplatform")
    Column(Modifier.fillMaxSize()) {
        val text =
            webViewState.let {
                "${it.pageTitle ?: ""} ${it.loadingState} ${it.lastLoadedUrl ?: ""}"
            }
        Text(text)
        WebView(
            state = webViewState,
            modifier = Modifier.fillMaxWidth().weight(1f),
        )
    }
}
```

**Comment by Matcha-xiaobin** [comment]
我想我知道是什么问题了，是我遗漏了一些东西，我没有为KCEF做配置，我现在先去为APP配置下KCEF。

**Comment by KevinnZou** [comment]
It looks wired. What's your Kotlin and Compose version? Additionally, did the kcef-bundle download successfully on your first launch? You could try to delete the kcef-bundle and redownload it.

**Comment by KevinnZou** [comment]
> 我想我知道是什么问题了，是我遗漏了一些东西，我没有为KCEF做配置，我现在先去为APP配置下KCEF。

Oh, I also forgot to mention that. You have to init the KCEF first and you can find the instructions [here](https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/README.desktop.md)

**Comment by Matcha-xiaobin** [comment]
@KevinnZou 您好，我按照你的说明文档去尝试，但出现以下错误：
Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.contentnegotiation.ContentNegotiation
请问我需要怎么解决这个问题？

**Comment by KevinnZou** [comment]
> @KevinnZou 您好，我按照你的说明文档去尝试，但出现以下错误： Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.contentnegotiation.ContentNegotiation 请问我需要怎么解决这个问题？

It looks like the problem of Ktor, you should follow the StackTrace to see what caused that problem.

**Comment by Matcha-xiaobin** [comment]
> > @KevinnZou 您好，我按照你的说明文档去尝试，但出现以下错误： Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.contentnegotiation.ContentNegotiation 请问我需要怎么解决这个问题？
> 
> It looks like the problem of Ktor, you should follow the StackTrace to see what caused that problem.

问题已经解决了，我看了一下，是因为我使用了最新beta版ktor，而这个库需要的文件，在最新beta版中没有，或者改名了。
目前我使用ktor 2.3.6版本，一切顺利。
感谢！
