### ISSUE TITLE
Terrible performance on Android

### ISSUE THREAD

**Issue by xmeaindes** [KevinnZou/compose-webview-multiplatform#71]
I ran an example on Google Pixel, which has absolutely no problems in Chrome. WebView is very slow

https://github.com/KevinnZou/compose-webview-multiplatform/assets/126922273/c76df869-4adf-4b72-95dd-2e8cd5a185fc

Version: 1.7.8

**Comment by flymedllva** [comment]
The problem seems to be related to `this.setLayerType(View.LAYER_TYPE_SOFTWARE, null)` added recently https://github.com/KevinnZou/compose-webview-multiplatform/pull/65. With or without `this.setLayerType(View.LAYER_TYPE_HARDWARE, null)` everything works correctly

**Comment by KevinnZou** [comment]
@flymedllva Thanks for your help! @xmeaindes In version 1.7.8, I have set the Software Layer as the default solution to address the https://github.com/KevinnZou/compose-webview-multiplatform/issues/64. I will switch to Hardware Layer and release the 1.8.0 today. Sorry for the inconvenience caused.

**Comment by KevinnZou** [comment]
@xmeaindes It has been fixed in version 1.8.0. Please have a try and let me know if you encounter any problems.
