### ISSUE TITLE
In iOS webview height is not becoming wrap content, 

### ISSUE THREAD

**Issue by sureshmaidaragi1919** [KevinnZou/compose-webview-multiplatform#77]
Hi There, we used this library in one of our KMM projects, in Android it works perfectly fine, but the issue in iOS it shows scrollable content, instead of making it wrap content

Android Screen shot without scrollabar
![Screenshot 2023-12-28 at 12 51 31 PM](https://github.com/KevinnZou/compose-webview-multiplatform/assets/28126457/6139b7dc-b3df-4c90-a041-0d31c32c3f63)

iOS  Screen shot with scrollbar, how to make it auto adjust according to the height of content
![Screenshot 2023-12-28 at 11 31 46 AM](https://github.com/KevinnZou/compose-webview-multiplatform/assets/28126457/df66ec46-c5e0-4a08-995a-c70f63f18dd7)

iOS video
 

https://github.com/KevinnZou/compose-webview-multiplatform/assets/28126457/961d8ced-9102-4376-8895-72eb186bc4f3

**Comment by KevinnZou** [comment]
@sureshmaidaragi1919 Hi, thanks for your feedback! Can you please provide the structure of your page? Are you using Webview to display only these three lines of text? If that's the case, would it be more suitable to use a fixed height instead? When the content of the Webview is unpredictable, allowing it to wrap the content might cause unexpected spacing issues and make other components hidden.

**Comment by sureshmaidaragi1919** [comment]
> @sureshmaidaragi1919 Hi, thanks for your feedback! Can you please provide the structure of your page? Are you using Webview to display only these three lines of text? If that's the case, would it be more suitable to use a fixed height instead? When the content of the Webview is unpredictable, allowing it to wrap the content might cause unexpected spacing issues and make other components hidden.


@KevinnZou 
Yes , but this three lines can become 10lines sometimes, so we can't keep fixed height
>Are you using Webview to display only these three lines of text? I would it be more suitable to use a fixed height instead?

**Comment by KevinnZou** [comment]
@sureshmaidaragi1919 I understand what you mean, and I also tried it myself and found that wrap content doesn't work. However, this seems to be a problem with Compose Multiplatform or within WKWebView itself, as it cannot calculate the height of the internal web content to determine its own height. It seems that your use case may not be very suitable for using WebView, and you may need to try other solutions to solve this problem.

**Comment by sureshmaidaragi1919** [comment]
> @sureshmaidaragi1919 I understand what you mean, and I also tried it myself and found that wrap content doesn't work. However, this seems to be a problem with Compose Multiplatform or within WKWebView itself, as it cannot calculate the height of the internal web content to determine its own height. It seems that your use case may not be very suitable for using WebView, and you may need to try other solutions to solve this problem.

I see thanks for quick response Kevinn

**Comment by CMingTseng** [comment]
> Hi There, we used this library in one of our KMM projects, in Android it works perfectly fine, but the issue in iOS it shows scrollable content, instead of making it wrap content
> 
> Android Screen shot without scrollabar ![Screenshot 2023-12-28 at 12 51 31 PM](https://private-user-images.githubusercontent.com/28126457/293157716-6139b7dc-b3df-4c90-a041-0d31c32c3f63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzY4NDUsIm5iZiI6MTcyMDM3NjU0NSwicGF0aCI6Ii8yODEyNjQ1Ny8yOTMxNTc3MTYtNjEzOWI3ZGMtYjNkZi00YzkwLWEwNDEtMGQzMWMzMmMzZjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE4MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjY2Q4ZmJmZWJhMTQ5NjI3YWVjYjc4MTg2NDEzOTgzMTA1NWY0OTBlOGI5N2NmZWU4YjdhNWUyNWViMTU5NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CEL0yYfaVCGttqPhv50lIEX2KUtCFPYZfvqPeU7xxSo)
> 
> iOS Screen shot with scrollbar, how to make it auto adjust according to the height of content ![Screenshot 2023-12-28 at 11 31 46 AM](https://private-user-images.githubusercontent.com/28126457/293147036-df66ec46-c5e0-4a08-995a-c70f63f18dd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzY4NDUsIm5iZiI6MTcyMDM3NjU0NSwicGF0aCI6Ii8yODEyNjQ1Ny8yOTMxNDcwMzYtZGY2NmVjNDYtYzVlMC00YTA4LTk5NWEtYzcwZjYzZjE4ZGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE4MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNWE2MTAxMWM0YTZmOGZjZGU5NjU2MTI3MDc1YzYyZDcyZjE2MGI2MDI2NDBiYjQwNTc2NGExZTI2MmIxNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d4zTYQM5iiC6J2c9eTe_Zc963BPOKWpIUBjBqCtgd9M)
> 
> iOS video
> 
>  Screen.Recording.2023-12-28.at.12.55.54.PM.mov

@sureshmaidaragi1919 

Hello Senior Developer,

I found this project because I need WebView and Adjust, and I read through various issues here. I noticed that you are using WebView and Adjust on iOS. I have been having configuration issues with this part myself. This is my project: https://github.com/cybernhl/webapp

Could you please guide me on how to configure it?

Thank you.

**Comment by Szczypiorek44** [comment]
Hey, does anyone found out how to resolve this problem?
How to set WebView's height to wrap content?
