### ISSUE TITLE
How to Disable Information in the Command Line

### ISSUE THREAD

**Issue by SnowCharmQ** [KevinnZou/compose-webview-multiplatform#78]
Hi there, could you please tell me how to make the command line not show the information.
I have tested set **logSeverity = KLogSeverity.Error** in the webSettings, however, the command line still outputs some INFO as shown below.
![image](https://github.com/KevinnZou/compose-webview-multiplatform/assets/82224175/8af1e0c9-1793-40e6-a554-6068bc784ba5)
Sometimes there are too much information to crash my IDE.

**Comment by KevinnZou** [comment]
@SnowCharmQ Thanks for your feedback. Are you certain that these pieces of information are being generated by my library? I do not generate this information in my library and have never seen it in my console. This is why setting `logSeverity` to `KLogSeverity.Error` is not effective.

**Comment by SnowCharmQ** [comment]
> @SnowCharmQ Thanks for your feedback. Are you certain that these pieces of information are being generated by my library? I do not generate this information in my library and have never seen it in my console. This is why setting `logSeverity` to `KLogSeverity.Error` is not effective.

Yeah, I think that these messages are generated by my application as I call console.log() (it will be outputted to the console in the frontend, but it will also be shown in my IDE when I use the WebView library), and other warnings in the web page.
But I just want to know whether there is an option that I can disable it, because currently there are a lot of messages in my IDE console as the figure shows. It sometimes turns out to be awful and crashes my IDE. I would really appreciate it if you could give me some advice to handle this issue or add a new feature to disable the output in my IDE.

**Comment by KevinnZou** [comment]
@SnowCharmQ Thanks for your explanation. If the messages come from your application, it would be better for you to control the log level from your side instead of my library. You can design `logSeverity` like `KLogSeverity` to determine whether the messages should be printed.
