### ISSUE TITLE
NullPointerException when url contains ä

### ISSUE THREAD

**Issue by rackaracka123** [KevinnZou/compose-webview-multiplatform#81]
Title

removed the ä and it works.

there are most likely more letters that also have this problem

**Comment by Mats-Hjalmar** [comment]
Update to this:

It works in the simulator with ä but not device

**Comment by KevinnZou** [comment]
@Mats-Hjalmar Thanks for your feedback. Which platforms are you running on? Or it fails on all three platforms?

**Comment by Mats-Hjalmar** [comment]
Only breaks on iOS 15 device.

**Comment by KevinnZou** [comment]
@Mats-Hjalmar It appears that iOS WKWebView does not support ä characters. Can you please encode the URL and test it on an iOS device?
