### ISSUE TITLE
Failed to load url error in compose desktop

### ISSUE THREAD

**Issue by amrmsaraya** [KevinnZou/compose-webview-multiplatform#85]
For a compose desktop application i get this error in `state.errorsForCurrentRequest` using the code sample in the [README.desktop.md](https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/README.desktop.md)
`ERR_ABORTED), WebViewError(code=-3, description=Failed to load url: https://github.com)`

Thanks for your efforts for this great library

**Comment by KevinnZou** [comment]
@amrmsaraya Thank you for your feedback! Which platform are you using? Have you followed the steps in [README.desktop.md](https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/README.desktop.md)? If you have, could you please provide the code on setting up the WebView? You can refer to [BasicWebViewSample](https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/sample/shared/src/commonMain/kotlin/com/kevinnzou/sample/BasicWebViewSample.kt) as a reference.

**Comment by amrmsaraya** [comment]
Thanks @KevinnZou for the fast response. actually i figured out the problem after using [BasicWebViewSample](https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/sample/shared/src/commonMain/kotlin/com/kevinnzou/sample/BasicWebViewSample.kt) as a reference like you said. The problem was that i was creating the `WebViewState` before `KCEF` is intialized even if i don't call the `WebView` composable until it's initilaized. So all i needed to do is creating the `WebViewState` after `KCEF` has been initialized.

Sorry for the inconvenience.
