### ISSUE TITLE
在Mac OS 上无法获取页面html内容

### ISSUE THREAD

**Issue by Matcha-xiaobin** [KevinnZou/compose-webview-multiplatform#86]
目前只试了下Mac os，windows未尝试。
在安卓和ios上一切正常。

以下是步骤：
1.  加载一个链接
2. 网页加载完成后，调用evaluateJavaScript()函数执行一段js代码
3. 获取js代码执行后返回的内容

在页面加载完成时做的事情：
```
    val webViewLoadingState = rememberWebViewState(curPageUrl)
    if (webViewLoadingState.loadingState == LoadingState.Finished) {
        LaunchedEffect(repeatCount) {
            // 去执行了 evaluateJavaScript() 
        }
    }
```

js代码：
```
evaluateJavaScript(
        """(function() {
                    var htmlText = document.documentElement.outerHTML;
                    return htmlText;
              })();"""
    ) { html ->
    // 判断页面内容的代码
}
```

最终我在回掉中得到的结果是：
![image](https://github.com/KevinnZou/compose-webview-multiplatform/assets/5775066/5af39dea-4793-42c3-ac1e-2a172a53bc04)

这不是我想要的内容。
我写了个定时循环，如果返回的内容不正确，则间隔0.3s会再次执行这段js，但返回的内容一直是上面的结果

**Comment by KevinnZou** [comment]
@Matcha-xiaobin Thanks for your feedback! I also reproduced the issue. After investing some time, it appears that the issue is related to the format of the executed JavaScript code. The code below will also result in undefined:
```
evaluateJavaScript(
        """(function() {
                    return 'html';
              })();"""
    ) { html ->
}
```


I'm not sure why the desktop doesn't accept that code format. @DatL4g, can you explain?

However, I have found a solution to your issue. You can choose to do either:
```
LaunchedEffect(state) {
    snapshotFlow { state.loadingState }
        .filter { it is LoadingState.Finished }
        .collect {
            navigator.evaluateJavaScript(
                """
                window.getHtml = function() {
                    return document.documentElement.outerHTML;
                    }
            """.trimIndent()
            )
            navigator.evaluateJavaScript(
                """
                window.getHtml();
                """.trimIndent()
            ) {
                Logger.i { "Sample evaluateJavaScript: $it" }
            }
        }
}
```
or simply:
```
navigator.evaluateJavaScript(
    """
    return document.documentElement.outerHTML;
    """.trimIndent()
) {
    Logger.i { "Sample evaluateJavaScript: $it" }
}
```

I apologize for any inconvenience caused by this issue. If you have any further questions, please let me know.

**Comment by Matcha-xiaobin** [comment]
> """
>     return document.documentElement.outerHTML;
>     """.trimIndent()

感谢您的回复，这个回复对我确实有用。

**Comment by DatL4g** [comment]
Please read the documentation, Desktop only supports function bodies.

I guess something like `function test() {...} test();` will work, but officially only the body is supported.
