### ISSUE TITLE
Listener Support

### ISSUE THREAD

**Issue by Shabinder** [KevinnZou/compose-webview-multiplatform#9]
There should be listener support, 
where one could listen to events like onLoadStop etc

**Comment by Shabinder** [comment]
By Listener I mean callbacks can work too.

**Comment by Shabinder** [comment]
Found there is Loading Events State, which shall do what I need.

**Comment by KevinnZou** [comment]
Yes, sorry for missing it in the ReadMe. Actually, besides the loading state, I am also planning to provide the callback for each loading event, like onLoadStop. However, I encountered some issues when I tried to implement it on the iOS platform. Normally, in raw iOS projects, we use WKNavigationDelegate to intercept navigation events. However, in multiplatform projects, it can only intercept the first navigation event. For further navigation, it cannot give any information. Thus, I can only give up that plan temporarily. I will go back to it when I solve other main issues. You are also welcome to submit a PR the solve that problem. Thanks again!
