### ISSUE TITLE
OpenGL crash

### ISSUE THREAD

**Issue by tomastiminskas** [KevinnZou/compose-webview-multiplatform#93]
Not sure if it's related with the library but after implementing it I started to get reports from users experiencing a crash with the following error message:

`void org.jetbrains.skiko.OpenGLLibraryKt.loadOpenGLLibraryWindows()`

Any help will be appreciated. Thanks in advance

**Comment by tomastiminskas** [comment]
@KevinnZou sorry for so many questions and feedback. I could solve the crash by upgrading compose plugin. But here is another issue I'm experiencing. Some Windows users are getting the **restart required** message every time they open the app and the KCEF download process is not starting. 

After some debug sessions we found that it works perfect when running app as an administrator, so I guess the issues is related with write permissions. Did you experience this issue before or have any idea on how to fix it? 

Thanks in advance

**Comment by KevinnZou** [comment]
@DatL4g Could you have a look at this issue?

**Comment by tomastiminskas** [comment]
@KevinnZou @DatL4g I was able to prevent the crash by upgrading `org.jetbrains.compose` plugin from version 1.5.1 to 1.5.11
